name: json2dart_dbffi
description: use json2dart_safe togethor to surppot the database for platform contains Android,Ios,Macos,Window and Linux，easy support.

version: 0.0.6
homepage: https://github.com/fastcode555/Json2Dart_Null_Safety/tree/master/json2dart_dbffi

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi:
  sqflite_common:
  path:
  json2dart_safe:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true