import 'package:book_reader/res/strings.dart';

const Map<String, String> languageZhHant = {
  Ids.educationalLiterature: '教育文獻',
  Ids.catalogue: '目錄',
  Ids.auto: '自動',
  Ids.reading: '閱讀',
  Ids.control: '控制',
  Ids.contents: '內容',
  Ids.swipe: '滑動',
  Ids.leaf: '葉',
  Ids.scroll: '滾動',
  Ids.tap: '點擊',
  Ids.flippingTheVolumeButton: '翻轉音量鍵',
  Ids.books: '書籍',
  Ids.bookshelf: '書架',
  Ids.english: '英文',
  Ids.saveAsNote: '另存為註釋',
  Ids.tooSmallFontIsNotGoodForProtectingYourEyes: '字體過小不利於保護您的眼睛!',
  Ids.sirTheFontHasReachedItsMaximumValue: '客官，字體已經達到最大值！ ',
  Ids.finish: '結束',
  Ids.font: '字體',
  Ids.importFont: '導入字體',
  Ids.confirm: '確認',
  Ids.addBooks: '添加書籍',
};
