import 'strings.dart';

const Map<String, String> languageEn = {
  Ids.educationalLiterature: 'Educational literature',
  Ids.catalogue: 'Catalogue',
  Ids.auto: 'AUTO',
  Ids.reading: 'READING',
  Ids.control: 'CONTROL',
  Ids.contents: 'CONTENTS',
  Ids.swipe: 'Swipe',
  Ids.leaf: 'Leaf',
  Ids.scroll: 'Scroll',
  Ids.tap: 'Tap',
  Ids.flippingTheVolumeButton: 'Flipping the volume button',
  Ids.books: 'Books',
  Ids.bookshelf: 'Bookshelf',
  Ids.english: 'ENGLISH',
  Ids.saveAsNote: 'SAVE AS NOTE',
  Ids.tooSmallFontIsNotGoodForProtectingYourEyes: 'Too small font is not good for protecting your eyes!',
  Ids.sirTheFontHasReachedItsMaximumValue: 'Sir, the font has reached its maximum value!',
  Ids.finish: 'finish',
  Ids.font: 'font',
  Ids.importFont: 'import font',
  Ids.confirm: 'Confirm',
  Ids.addBooks: 'Add books',
};
