import 'strings.dart';

const Map<String, String> languageZhHans = {
  Ids.educationalLiterature: '教育文献',
  Ids.catalogue: '目录',
  Ids.auto: '自动',
  Ids.reading: '阅读',
  Ids.control: '控制',
  Ids.contents: '内容',
  Ids.swipe: '滑动',
  Ids.leaf: '叶',
  Ids.scroll: '滚动',
  Ids.tap: '点击',
  Ids.flippingTheVolumeButton: '翻转音量键',
  Ids.books: '书籍',
  Ids.bookshelf: '书架',
  Ids.english: '英文',
  Ids.saveAsNote: '另存为注释',
  Ids.tooSmallFontIsNotGoodForProtectingYourEyes: '字体过小不利于保护您的眼睛!',
  Ids.sirTheFontHasReachedItsMaximumValue: '客官，字体已经达到最大值！',
  Ids.finish: '结束',
  Ids.font: '字体',
  Ids.importFont: '导入字体',
  Ids.confirm: '确认',
  Ids.addBooks: '添加书籍',
};
