name: json2dart_safe
description: A plugin to generated json with Null-Safety feature and safe convert with default value.

version: 1.5.4
homepage: https://github.com/fastcode555/Json2Dart_Null_Safety.git

environment:
  sdk: '>=2.19.1 <3.0.0'
