import 'package:gesound/res/strings.dart';

const Map<String, String> languageZhHant = {
  Ids.cancel: '取消',
  Ids.import: '導入',
  Ids.playlist: '播放列表',
  Ids.setUp: '設置',
  Ids.areYouSure: '你確定嗎？ ',
  Ids.confirm: '確認',
  Ids.editCategoryName: '編輯類別名稱',
  Ids.feedback: '反饋',
  Ids.language: '語言',
  Ids.done: '完成',
  Ids.delete: '刪除',
  Ids.defaultx: '默認',
  Ids.novel: '小說',
  Ids.close: '關閉',
  Ids.songs: '%s 首歌曲',
  Ids.newPlaylist: '新播放列表',
  Ids.createANewPlaylist: '創建一個新的播放列表',
  Ids.renamePlaylist: '重命名播放列表',
  Ids.createANewCategory: '新建分類',
  Ids.allCategories: '所有類別',
  Ids.newCategory: '新品類',
  Ids.category: '類別',
  Ids.submitFailed: '提交失敗！ ',
  Ids.selectACategory: '選擇一個類別',
  Ids.submitSuccessfully: '提交成功！ ',
  Ids.replay: '重播',
  Ids.resume: '繼續',
  Ids.localImportDesc: '打開本地文件，選擇資源並將其導入應用程序進行播放。',
  Ids.linkImportDesc: '輸入帶有音頻鏈接的 URL，我們將識別音頻文件供您播放。',
  Ids.cloudImportDesc: '鏈接雲服務，隨時隨地聽音樂，不佔用額外設備空間。',
  Ids.stroage: '存儲',
  Ids.theSoftwareRunsTooLaggyAndCrashes: '該軟件運行太慢並崩潰。',
  Ids.unableToImportLocalFile: '無法導入本地文件。',
  Ids.canNotPlayTheSongs: '無法播放歌曲。',
  Ids.insufficientInterfaceExperience: '界面體驗不足。',
  Ids.others: '其他。',
  Ids.top: '置頂',
  Ids.theCategoryNameAlreadyExists: '該分類名已經存在',
  Ids.edit: '編輯',
  Ids.changeSucceeded: '更改成功',
  Ids.createdSuccessfully: '創建成功',
  Ids.deleteCategoryConfirm: '當前\n類別下有列表：%s，總可玩資源：%s。\n一旦刪除，將無法恢復。 \n你想確認刪除嗎？',
  Ids.playlistNameAlreadyExists: '播放列表名稱已存在',
  Ids.pleaseSelectAFeedbackType: '請選擇反饋類型',
  Ids.pleaseEnterFeedback: '請輸入反饋內容',
  Ids.submittedSuccessfully: '提交成功',
  Ids.thePlaylistNameAlreadyExists: '該播放列表名稱已經存在',
  Ids.deletePlaylistConfirm: '已刪除的數據無法恢復，\n您確定要刪除當前列表。\n',
  Ids.pleaseImportDesc: '請先選需要導入的內容',
  Ids.addSongs: '添加歌曲',
  Ids.deleteSongDescription: '刪除數據不可恢復，確認刪除當前歌曲嗎？',
  Ids.selectMoveSongFirst: '請先選擇需要移動的歌曲！',
  Ids.addSongSuccessfully: '添加歌曲成功',
  Ids.importSuccessful: '導入成功',
  Ids.scanQrcode: '掃描二維碼',
  Ids.noQrCodeFound: '未找到二維碼',
  Ids.noPermission: '沒有權限',
  Ids.unableToResolveLink: '無法解析鏈接%s',
  Ids.theQrCodeIsInvalid: '該二維碼無效',
  Ids.songIsLoading: '歌曲正在加載中！',
  Ids.nowPlayingWithCount: '正在播放 (%s)',
  Ids.pleaseSelectReportAProblemFirst: '請先選擇報告問題！',
  Ids.pleaseSelectAClosingTime: '請選擇關閉時間',
  Ids.startTheTimer: '開始計時',
  Ids.noPlayTasksYet: '暫無播放任務',
  Ids.addedSuccessfully: '添加成功',
};
