import 'strings.dart';

const Map<String, String> languageEn = {
  Ids.cancel: 'Cancel',
  Ids.import: 'Import',
  Ids.playlist: 'Playlist',
  Ids.setUp: 'Set Up',
  Ids.areYouSure: 'Are you sure?',
  Ids.confirm: 'Confirm',
  Ids.editCategoryName: 'Edit category name',
  Ids.feedback: 'Feedback',
  Ids.language: 'Language',
  Ids.delete: 'Delete',
  Ids.defaultx: 'Default',
  Ids.close: 'Close',
  Ids.songs: '%s songs',
  Ids.newPlaylist: 'New Playlist',
  Ids.createANewPlaylist: 'create a new playlist',
  Ids.renamePlaylist: 'Rename Playlist',
  Ids.createANewCategory: 'Create a new category',
  Ids.allCategories: 'All Categories',
  Ids.newCategory: 'New category',
  Ids.category: 'Category',
  Ids.submitFailed: 'Submit Failed!',
  Ids.selectACategory: 'Select a Category',
  Ids.novel: 'Novel',
  Ids.submitSuccessfully: 'Submit successfully!',
  Ids.replay: 'Replay',
  Ids.resume: 'Resume',
  Ids.localImportDesc: 'Open the local file, select the resource and import it into the app for playback.',
  Ids.linkImportDesc: 'Enter the URL with the audio link and we will identify the audio file for you to play.',
  Ids.cloudImportDesc:
      'Link to cloud services to listen to music anytime, anywhere without taking up additional device space.',
  Ids.theSoftwareRunsTooLaggyAndCrashes: 'The software runs too laggy and crashes.',
  Ids.stroage: 'Storage',
  Ids.unableToImportLocalFile: 'Unable to import local file.',
  Ids.canNotPlayTheSongs: 'Can not play the songs.',
  Ids.insufficientInterfaceExperience: 'Insufficient interface experience.',
  Ids.others: 'Others.',
  Ids.top: 'Pin',
  Ids.theCategoryNameAlreadyExists: 'The category name already exists',
  Ids.changeSucceeded: 'Change succeeded',
  Ids.edit: 'Edit',
  Ids.createdSuccessfully: 'Created successfully',
  Ids.deleteCategoryConfirm:
      'There are the lists under the current \ncategory: %s, total playable resources: %s.\nOnce deleted, it cannot be recovered. Do\nyou want to confirm the deletion?',
  Ids.playlistNameAlreadyExists: 'playlist name already exists',
  Ids.pleaseSelectAFeedbackType: 'Please select a feedback type',
  Ids.pleaseEnterFeedback: 'Please enter feedback',
  Ids.submittedSuccessfully: 'Submitted successfully',
  Ids.thePlaylistNameAlreadyExists: 'The playlist name already exists',
  Ids.deletePlaylistConfirm: 'Deleted data cannot be recovered.\nAre you sure you want to delete the \ncurrent list.',
  Ids.pleaseImportDesc: 'Please select the content to be imported first',
  Ids.addSongs: 'Add songs',
  Ids.deleteSongDescription: 'Deleted data cannot be recovered. Are you sure you want to delete the current song?',
  Ids.selectMoveSongFirst: 'Please select the song you want to move first!',
  Ids.addSongSuccessfully: 'Add song successfully',
  Ids.importSuccessful: 'Import successful',
  Ids.scanQrcode: 'Scan QRCode',
  Ids.noQrCodeFound: 'No QR code found',
  Ids.noPermission: 'No Permission',
  Ids.unableToResolveLink: 'Unable to resolve link %s',
  Ids.theQrCodeIsInvalid: 'The QR code is invalid',
  Ids.songIsLoading: 'Song is loading!',
  Ids.nowPlayingWithCount: 'Now Playing (%s)',
  Ids.pleaseSelectReportAProblemFirst: 'Please select report a problem first!',
  Ids.pleaseSelectAClosingTime: 'Please select a closing time',
  Ids.startTheTimer: 'start the timer',
  Ids.noPlayTasksYet: 'No play tasks yet',
  Ids.addedSuccessfully: 'Added successfully',
  Ids.done: 'Done',
};
